Fix Parser.new to load content from file
lumoslabs/paxmex pull request #9
Opened 2020-01-31 15:29 UTC by kamenlitchev

When using `Parser.new(path_to_file, path_to_schema)`, `path_to_file` was handled verbatim as string, and not as a file path.

2020-02-06 21:42 UTC, camertron requested changes
Hey @kamenlitchev, thanks for the pull request!

I'm not sure I like the fact that the `data` parameter can be either a path or a string. I know that's already how `schema` is treated, but I'd rather not turn that into a pattern.

Why not just pass the data contents to the parser, i.e. `Parser.new(File.read(data_path), schema_path)`?

2020-05-28 13:48 UTC, kamenlitchev commented
Sorry about the late reply!

So, basically it appeared as a regression to me because:

- I upgraded from 1.2 to 2.0 and the code stopped working (in 1.2 you could pass path and it got expanded: https://github.com/lumoslabs/paxmex/blob/1.2.0/lib/paxmex/parser.rb#L17)
- [README](https://github.com/lumoslabs/paxmex#user-defined-schema) says you can use `Parser.new` with path: `parser = Parser.new(path_to_raw_file, path_to_schema_file)`

2020-05-28 17:49 UTC, camertron commented
@kamenlitchev ah ok, I understand. Can we add a method like `Parser.open` or `Parser.from_file` to handle the path case then?

2020-06-08 13:01 UTC, kamenlitchev commented
Sure. I will see to adding it

2022-04-14 13:24 UTC, closed without merging